### ISSUE TITLE
Build fails with undefined types

### ISSUE THREAD

**Issue by mans0954** [jgensler8/terraform-provider-minikube#2]
Following the README instructions, the build currently fails due to the `cluster.MachineConfig`, `bootstrapper.KubernetesConfig` and `cluster.Config` types being undefined.
```
go build -o example/plugins/terraform-provider-minikube
# github.com/jgensler8/terraform-provider-minikube/minikube
minikube/resource_minikube.go:368:12: undefined: cluster.MachineConfig
minikube/resource_minikube.go:426:22: undefined: bootstrapper.KubernetesConfig
minikube/resource_minikube.go:447:19: undefined: cluster.Config
minikube/resource_minikube.go:627:42: undefined: cluster.Config
minikube/resource_minikube.go:628:9: undefined: cluster.Config
minikube/resource_minikube.go:649:31: undefined: cluster.Config
```
This appears to be because of a reorganisation of the minikube code [1].

I'll submit a pull request which I believe fixes this shortly.

Thanks.

Christopher
[1] https://github.com/kubernetes/minikube/commit/0fa64b3bd8b2602d41f60f2dc81dee1c451f3fd7

**Comment by jgensler8** [comment]
Hello Christopher! Thank you for taking interest in this repository and raising an issue.

Did you use the glide package manager to install dependencies? I believe this should have locked minikube to [a particular version](https://github.com/jgensler8/terraform-provider-minikube/blob/master/glide.yaml#L15-L16). Perhaps I didn't set glide up properly as I am missing the glide lock file...

**Comment by jgensler8** [comment]
@mans0954 I think this may have been fixed in some recent commits. I have also added binary publishing so please check out the release page for more information: https://github.com/jgensler8/terraform-provider-minikube/releases/tag/v0.4.0
