### ISSUE TITLE
Failing on glide install

### ISSUE THREAD

**Issue by rmn36** [jgensler8/terraform-provider-minikube#4]
Getting these errors when trying to run the glide install command
```
$ glide install 
[ERROR] Error scanning k8s.io/kube-openapi/pkg/util/proto: cannot find package "." in:
        /Users/<USER>/.glide/cache/src/https-k8s.io-kube-openapi/pkg/util/proto
[ERROR] Error scanning github.com/docker/docker/pkg/homedir: cannot find package "." in:
        /Users/rnowacoski/.glide/cache/src/https-github.com-docker-docker/pkg/homedi
```

**Comment by jgensler8** [comment]
Hello @rmn36,

Sorry for the delay here. I was able to look at this over the weekend and confirmed the error you are getting. I have looked at a few of the forks of this repo and there may be a few that have fixed this issue already. This one has been updated 19 days ago: https://github.com/shaneramey/terraform-provider-minikube/blob/master/glide.yaml

Let me know if those projects end up fixing this issue. I suppose I could try and pull request back into this repo...

-Jeff

**Comment by rmn36** [comment]
Able to install with glide but I still can't build

```
# github.com/jgensler8/terraform-provider-minikube/minikube
minikube/resource_minikube.go:368:12: undefined: cluster.MachineConfig
minikube/resource_minikube.go:426:22: undefined: bootstrapper.KubernetesConfig
minikube/resource_minikube.go:447:19: undefined: cluster.Config
minikube/resource_minikube.go:627:42: undefined: cluster.Config
minikube/resource_minikube.go:628:9: undefined: cluster.Config
minikube/resource_minikube.go:649:31: undefined: cluster.Config
```

**Comment by rmn36** [comment]
@jgensler8 I'm not looking to develop on this provider, just use it locally. Is there a way for you to share the binary/publish it somewhere for consumption without having to build locally?

**Comment by shaneramey** [comment]
I put a binary in my fork if you check the releases. I’m planning on doing
a PR to this repo one day soon.

**Comment by shaneramey** [comment]
I created PR https://github.com/jgensler8/terraform-provider-minikube/pull/5 to move from Glide to go modules.

**Comment by jgensler8** [comment]
I've merged the PR and am going to spend the next few hours adding CI and the ability to publish binaries.

**Comment by jgensler8** [comment]
@rmn36 I wasn't aware the the "fix" keyword would close this issue. Travis has uploaded binaries to the latest release. Please take a look at https://github.com/jgensler8/terraform-provider-minikube/releases/tag/v0.4.0 and see if that can work for your use case!
